# Generated by Django 4.2.2 on 2023-10-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_list_name_list_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="name",
        ),
    ]
