# Generated by Django 4.2.2 on 2023-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0009_alter_item_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(),
        ),
    ]
